### ISSUE TITLE
 Error sending the query 'modules' in vue-apollo

### ISSUE THREAD

**Issue by jojobyte** [vuejs/vue-curated-client#3]
Looks like https://curated.vuejs.org/ does not work with [DuckDuckGo Plus](https://addons.mozilla.org/en-US/firefox/addon/duckduckgo-for-firefox/) addon in firefox. This is a recent development.

> Error sending the query 'modules' vue-apollo.esm.js:2645

![firefox_error](https://user-images.githubusercontent.com/184880/34916948-c7bfb0b6-f8fc-11e7-8919-55d426cab477.png)

**Comment by olegkorol** [comment]
I can reproduce the same error on Firefox Developer Edition with the DuckDuckGo Privacy Essentials extension:

![image](https://user-images.githubusercontent.com/13587499/35399859-910e0ed0-01f5-11e8-881c-84277f5e6ec0.png)

**Comment by Akryum** [comment]
I don't think we can do much about this. It's not a tracker, maybe there is a 'report an issue' button somewhere on your extension.
